# Generated by Django 5.1.5 on 2026-03-02 14:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', max_length=500),
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the attachment', max_length=200)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('video', 'Video File'), ('audio', 'Audio File'), ('other', 'Other')], default='pdf', max_length=10)),
                ('file_size', models.CharField(blank=True, help_text='e.g., 2.5 MB', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
